version: '3.7'
services:
  metaland-accounts:
    container_name: metaland-accounts
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./mtl_accounts:/mtl_accounts
    environment:
      - OAUTHLIB_INSECURE_TRANSPORT=${OAUTHLIB_INSECURE_TRANSPORT}
      - MY_CLIENT_ID=${MY_CLIENT_ID}
      - MY_CLIENT_SECRET=${MY_CLIENT_SECRET}
      - MY_CLIENT_TENANT=${MY_CLIENT_TENANT}
      - REDIRECT_URL=${REDIRECT_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=mtl_postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REDIS_HOST=mtl_redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=${REDIS_DATABASE}

  mtl_redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: mtl_redis
    hostname: mtl_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  mtl_postgresql:
    image: postgres
    restart: always
    container_name: mtl_postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
